version: '3.9'

services:
  caddy:
    image: caddy:2.6.2-alpine
    restart: unless-stopped
    command: caddy reverse-proxy --from https://dev.aleksandrslarionovs.com --to http://frontend:3000
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
    depends_on:
      - frontend
    networks:
      - node-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend
    environment:
      - NODE_ENV
    volumes:
      - /usr/src/node-app/node_modules
      - .:/usr/src/node-app
    command: CMD tail -f /dev/null
    networks:
      - node-network
volumes:
  caddy:
    external: true
networks:
  node-network:
    driver: bridge
